#!/bin/sh /etc/rc.common

# start after and stop before networking
START=12
STOP=89

USE_PROCD=1
PROG=/usr/bin/iperf3

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -s
	procd_close_instance
}
